[book]
authors = ["hencter"]
language = "zh"
multilingual = false
src = "src"
title = "学有未达"
theme = "theme"
description = "亦幸的网络笔记、知识图谱。"
# fold = [""]

[output.html]
# additional-css = ["css/custom.css"]

[output.html.print]
# enable = false # 打印支持 

[output.html.fold]
enable = true # 侧栏折叠支持
level = 1 # 折叠级数